### ISSUE TITLE
Setup Docker containers

### ISSUE THREAD

**Issue by deshraj** [Cloud-CV/Fabrik#130]
## Current Scenario

Currently setting up Fabrik on a local machine for development requires running a lot of commands. We want to setup the docker containers so that setting up Fabrik is not pain. 

## Deliverables

A basic setup that fulfills the following requirements:

- [ ] Different containers for Postgres, NodeJS and Django
- [ ] Add instructions in README

Please comment for if you have questions.

**Comment by blazejkw** [comment]
Hi @deshraj,

can I take a look on this ?

Regards

**Comment by deshraj** [comment]
@blazejkw, sure. Please let me know if you have questions.

**Comment by HugoHugo** [comment]
Can I take a look at this too?

**Comment by blazejkw** [comment]
Hello @deshraj,

sorry for being late I was quite busy this week.

HOWTO:
`
git clone ...
cd Fabrik/
docker build . -t frontend:latest
docker-compose up
`
I'd like to propose some PR with the POC of containers and stuff. To be honest it was quite hard to prepare this but I hope this is a right approach. I think it's a good idea to first build container with a compiled 'caffe' etc. Since it takes quite a lot of time and I guess it's nice to have this image build once for multiple use. Honestly I have no idea how to separate django and nodejs. Feel free to propose some solution If You wish.

Ofc this code need some improvements. I guess we can parametrize Dockerfile etc. Also please check if the package list is valid and all of them are needed.

Redards,
Blazej Kwasniak

**Comment by deshraj** [comment]
@blazejkw: thanks for the update. 

> I'd like to propose some PR with the POC of containers and stuff. To be honest it was quite hard to prepare this but I hope this is a right approach. I think it's a good idea to first build container with a compiled 'caffe' etc. Since it takes quite a lot of time and I guess it's nice to have this image build once for multiple use. Honestly I have no idea how to separate django and nodejs. Feel free to propose some solution If You wish.

Having a basic setup first sounds good to me. We can segregate the different containers later. Also, you can go ahead and open a PR for the same. We can iterate and discuss on that PR. 
I also agree that we should have a container compiled with 'caffe' since it takes a lot of time to build.

> Ofc this code need some improvements. I guess we can parametrize Dockerfile etc. Also please check if the package list is valid and all of them are needed.

Please open the PR and then I will have a better sense what are you talking about. :)

**Comment by deshraj** [comment]
@blazejkw any update on this?

**Comment by blazejkw** [comment]
Hi @deshraj,

well I did some changes few days ago :)  Please take a look on  #133 and commit

https://github.com/Cloud-CV/Fabrik/pull/133/commits/f2d0ddde6eef058bad81aa5dac54c49ede03c974

Regards,
Blazej

**Comment by trexdinosaur** [comment]
@deshraj , @blazejkw : Is this in a working state? If not, can I work on this as a GCI task in getting this to a working state?

Thanks

**Comment by PalashTanejaPro** [comment]
@trexdinosaur I am already working on it.

**Comment by PalashTanejaPro** [comment]
@deshraj Please take a look at #172. I have fulfilled all your requirements

**Comment by saurabhpal97** [comment]
Is anyone workin on this issue?

**Comment by deshraj** [comment]
@saurabhpal97: it looks like the current PullRequests are not working properly. So, I started working on it. You can see the relevant comment here: https://github.com/Cloud-CV/Fabrik/pull/172#issuecomment-369419562

Please feel free to work on it if interested.
